name: flutter_notification
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.1
  font_awesome_flutter: ^9.1.0
  flutter_local_notifications: ^8.0.0
  date_picker_timeline: 
  flutter_native_timezone:
  intl: 
  google_fonts:
  sqflite:
  awesome_notifications: ^0.0.6+10
  get_storage: ^2.0.3
  equatable: ^2.0.5
  flutter_easyloading: ^3.0.5
  flutter_staggered_animations:
  firebase_core: ^2.7.1
  cloud_firestore: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "lancher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"
  adabtive_icon_background: "assets/app_icon_background.png"
  adaptive_icon_foreground: "assets/app_icon_foreground.png"
flutter:

  uses-material-design: true

  assets:
    - images/
